#!/bin/bash
set -e


source ./functions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control gdm3
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
    ./debtemplate/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/get-template \
    > ./debian/get-template
chmod 755 ./debian/get-template

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/settings.install \
    > ./debian/${CODENAME_SAFE}-gdm3-settings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/settings.postinst \
    > ./debian/${CODENAME_SAFE}-gdm3-settings.postinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/settings.triggers \
    > ./debian/${CODENAME_SAFE}-gdm3-settings.triggers
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/settings.prerm \
    > ./debian/${CODENAME_SAFE}-gdm3-settings.prerm
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    template/10-gdm3-settings \
    > ./10-gdm3-settings


exit 0
